### ISSUE TITLE
Feature: flathub.org flatpak package

### ISSUE THREAD

**Issue by daniel-wtd** [blackhole89/notekit#54]
Hi,

I just recently discovered your application and I must say, it is woooonderful.
I strongly suggest to package a flatpak app for flathub.org. This will make the application so much more discoverable and many many more will see it. 

I am 100% sure, it will land on the editors choice very fast.

**Comment by blackhole89** [comment]
Thanks!

Flatpak has been suggested before (#42), but my last attempt to create a package ended in more than a day sunk into reading documentation with nothing to show for it, so at this point I'm kind of reluctant to spend more time on it myself, especially considering that there are multiple different systems of the kind (AppImage, Snap...) which all have been requested and all seem to be fraught with their own difficulties. (With Flatpak, I vaguely remember struggling with packaging up all Gtk+ dependencies, and with making it be able to read/write from the host file system.)

I'd still be very grateful for any pull requests with the appropriate build scripts.

**Comment by sp1ritCS** [comment]
I gave it a shot. The hard thing will be to compile gtksourceviewmm. This is what I came up with, but it fails with
```
Package 'configure: error: Package requirements (atk >= 1.18 glibmm-2.64 >= 2.63.1) were not met:

Package 'glibmm-2.64', required by 'virtual:world', not found
```
during the compilation of atkmm, even though glibmm v. 2.64.2 is built.

**com.github.blackhole89.notekit.yaml** (less important atm, will not work anyways as it does not install the data & sourceview dirs):
```yaml
app-id: com.github.blackhole89.notekit
command: notekit
runtime: org.gnome.Platform
runtime-version: '3.38'
sdk: org.gnome.Sdk
finish-args:
  - --socket=x11,
  - --device=dri
modules:
  - name: jsoncpp
    buildsystem: meson
    sources:
      - type: git
        url: https://github.com/open-source-parsers/jsoncpp
  - gtksourceviewmm.yaml 
  - name: notekit
    sources: 
      - type: git
        url: https://github.com/blackhole89/notekit.git
    buildsystem: cmake
```

**gtksourceviewmm.yaml** (If this works, the rest should be easy):
```yaml
modules:
  - name: mm-common
    sources: 
      - type: archive
        url: http://ftp.gnome.org/pub/GNOME/sources/mm-common/1.0/mm-common-1.0.2.tar.xz
        sha256: a2a99f3fa943cf662f189163ed39a2cfc19a428d906dd4f92b387d3659d1641d
    buildsystem: meson
  - name: graphviz
    sources:
      - type: git
        url: https://gitlab.com/graphviz/graphviz.git
    buildsystem: autotools

  - name: sigc++
    sources:
      - type: git
        url: https://github.com/libsigcplusplus/libsigcplusplus.git
        tag: 2.10.4
    buildsystem: meson
  - name: glibmm
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/glibmm.git
        tag: 2.64.2
    buildsystem: meson
  - name: cairomm
    sources: 
      - type: git
        url: git://git.cairographics.org/git/cairomm
        tag: 1.14.2
    buildsystem: autotools 
  - name: pangomm
    sources: 
      - type: git
        url: https://gitlab.gnome.org/GNOME/pangomm.git
        tag: 2.42.1
    buildsystem: meson
  - name: atkmm
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/atkmm.git
        commit: 5a420b4c62158e7f71796cb4a73532f91f1ebb5a
    buildsystem: autotools
  - name: gtkmm
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/gtkmm.git
        tag: 3.24.1
    buildsystem: autotools
name: gtksourceviewmm
sources: 
  - type: git
    url : https://gitlab.gnome.org/GNOME/gtksourceviewmm.git
    tag: 3.21.3
buildsystem: autotools
```
@bilelmoussaoui you offered to help in #42 . Could you take I look at this?
